const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94776928548"
const SESSION_ID = "PRABATH-MD~4QwiGCjY#GtrwHao3SSUmSsAaWgiisgO8MvjiDmJDr1dcWKodnX4"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
